spring.application.name=asistencia

# ===============================
# CONFIGURACION DE BASE DE DATOS (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/asistencia_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Boot respeta las tablas existentes y solo actualiza si hay cambios
spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080
